name: Create env file for flutter
description: Action creates special file for secrets and environmental variables

inputs:
  target_dir:
    description: Provide directory where env file should be created
    required: true

runs:
  using: "composite"
  steps:
  - name: Make .env.dev file
    uses: SpicyPizza/create-envfile@v1.3
    with:
      directory: ${{ inputs.target_dir }}
      file_name: .env.dev
  - name: Make .env.production file
    uses: SpicyPizza/create-envfile@v1.3
    with:
      directory: ${{ inputs.target_dir }}
      file_name: .env.production
      envkey_API_URL: https://ccquartersapi.azurewebsites.net
      envkey_PROJECT_ID: ccquartersmini
      envkey_AUTH_DOMAIN: ccquartersmini.firebaseapp.com
      envkey_DATABASE_URL: https://ccquartersmini-default-rtdb.europe-west1.firebasedatabase.app
      envkey_STORAGE_BUCKET: ccquartersmini.appspot.com
      envkey_API_KEY_WEB: AIzaSyARWCmfQw6xFBcbh9YdfL2lPabQEujzZDo
      envkey_APP_ID_WEB: 1:642205480758:web:8ba3bc1378a0f791e8a597
      envkey_MESSAGING_SENDER_ID_WEB: 642205480758
      envkey_MEASUREMENT_ID_WEB: G-JGVW96TE2W
      envkey_API_KEY_MOBILE: AIzaSyB-lIQR7r8WcbvE3ZHT7x7B5gRWCYldY2A
      envkey_APP_ID_MOBILE: 1:642205480758:android:0fcc7883ea8913f2e8a597
      envkey_MESSAGING_SENDER_ID_MOBILE: 642205480758
  - name: Check
    run: |
          head ${{ inputs.target_dir }}/.env.dev
          head ${{ inputs.target_dir }}/.env.production
