name: Building and deploying CCQuarters Web App to Azure Web App

on:
 push:
   branches:
     - master
 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest

   defaults:
     run:
        working-directory: client/

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Create env file
       uses: ./.github/actions/create_env_file
       with:
          target_dir: client/env/

     - name: Set up Node.js version
       uses: actions/setup-node@v1
       with:
         node-version: '20.x'

     - name: Set up Flutter
       uses: subosito/flutter-action@v2
       with:
          flutter-version: '3.x' # Replace with your desired Flutter version

     - name: Flutter web build
       run: flutter build web

     - name: install express
       run: npm install -g express-generator

     - name: run express
       run: express -f

     - name: delete app.js
       run: rm -f app.js

     - name: rename app.js
       run: mv express_app.js app.js

     - name: npm install, build, and test
       run: |
         ls
         npm install
         npm run build --if-present
         npm run test --if-present
     - name: Upload artifact for deployment job
       uses: actions/upload-artifact@v2
       with:
         name: node-app
         path: client/

 deploy:
   runs-on: ubuntu-latest
   needs: build
   environment:
     name: 'Production'
     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

   steps:
     - name: Download artifact from build job
       uses: actions/download-artifact@v2
       with:
         name: node-app

     - name: 'Deploy to Azure Web App'
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v2
       with:
         app-name: 'CCQuarters'
         publish-profile: ${{ secrets.CCQUARTERS_PUBLISH_PROFILE }}
         package: .
