name: Build and deploy app to Azure Web App - CCQuarters

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        uses: ./.github/actions/create_env_file
        with:
          target_dir: client/env/

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          web: true
          with-web-build: true
          cache: true

      - name: Flutter get dependencies
        run: flutter pub get
        
      - name: Build and Test
        run: flutter build web
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CCQuarters'
          slot-name: 'production'
          publish-profile: ${{ secrets.CCQUARTERS_PUBLISH_PROFILE }}
          package: '.\build\web'
