name: Build and deploy app to Azure Web App - CCQuarters

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        uses: ./.github/actions/create_env_file
        with:
          target_dir: client/env/

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          web: true
          with-web-build: true
          cache: true

      - name: Flutter get dependencies
        run: flutter pub get
        
      - name: Build
        run: flutter build web

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .webapp
          path: client/build/web
      
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .webapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CCQuarters'
          publish-profile: ${{ secrets.CCQUARTERS_PUBLISH_PROFILE }}
          package: '.'
